name: 'Verify HTML Headings'
description: 'Verifies that the Heading levels in HTML documents are in a valid order'
outputs:
  branch: # output will be available to future steps
    description: 'url to branch'
runs:
  using: 'node16'
  main: 'dist/index.js'
